### PR TITLE
Remove more dead code.

### PR DESCRIPTION
**Pull request by johnworth**
Removes support for pinging the service over AMQP. We never use it and the intended use case is better served by kubernetes.

I also removed what appeared to be a redundant query that was getting run for each job and just chewed up time.

### CODE REVIEW

**Comment by johnworth** [comment]
The linting failure seems...weird. Not sure it's something actually wrong with the code.

**Review by yeea — COMMENTED** [review]
LGTM 🚢 :

**Review by yeea — APPROVED** [review]
Shoulda selected `approval` on the earlier comment, oop

**Review by slr71 — APPROVED** [review]
The code looks good to me. I think that lint failure is safe to ignore.

**Pull request merged**
